export type {
  AstroErrorDetail,
  AstroExactFloat,
  AlmanacCause,
  AngleCause,
  BodyObservationCause,
  ObserveCause,
  EventFinderCause,
  FrameTransformCause,
  SunMoonCause,
  SpkErrorCause,
} from "../pkg/sidereon.js";
export type {
  ScalarObservableErrorDetail,
  VelocityErrorDetail,
  VelocityRangeErrorDetail,
} from "../pkg/sidereon.js";

// Companion types for the WebAssembly bindings, reachable as
// `@neilberkman/sidereon/types`.
//
// The IONEX declarations are generated into the package's own
// `sidereon.d.ts` from the `typescript_custom_section` in `src/ionex.rs`, which
// is also what the `unchecked_return_type` / `unchecked_param_type` attributes
// on the bindings resolve against. They are re-exported here rather than
// restated, so the two cannot drift apart.

export type {
  EcefToLla,
  IonexAssumedMapping,
  IonexAssumedMappingKind,
  IonexCoverageError,
  IonexCoverageErrorKind,
  IonexCoveragePolicy,
  IonexDiagnosticEpoch,
  IonexHeader,
  IonexHeaderInput,
  IonexMapCube,
  IonexMappingDeclaration,
  IonexMappingFunction,
  IonexMappingPolicy,
  IonexMissingNodePolicy,
  IonexMissingNodes,
  IonexNodeGap,
  IonexParseResult,
  IonexSlantBatchResult,
  IonexSlantDelayEvaluation,
  IonexSlantDelayStatus,
  IonexSlantPolicyInput,
  IonexSlantPolicyLike,
  IonexSlantRefusal,
  IonexSlantRequest,
  IonexWarning,
  IonexWriterErrorDetail,
  TecGridErrorDetail,
  TecGridEvaluation,
  TecGridSamples,
  TecGridSamplesInput,
  TecSample,
} from "../pkg/sidereon.js";

export type {
  InertialImuSampleInput,
  InertialImuSpec,
  InertialCalibration,
  InertialBias,
  InertialRateRandomWalk,
  InertialErrorModel,
  CorrectedImuIncrementInput,
  InertialImuSample,
  InertialNavState,
  InertialNavStateInput,
  InertialSimulatorOptions,
  InertialSimulationResult,
  InertialQuaternion,
  InertialDcm,
  InertialMechanizationConfig,
  InertialMechanizationInput,
  Wgs84GravityConstants,
  InertialErrorDetail,
  InertialAttitude,
  StationDisplacementRequest,
  StationDisplacementResult,
  StationDisplacementBatchRequest,
  StationDisplacementBatchRow,
  TideErrorDetail,
  TideInputKind,
  FrameTransformErrorDetail,
  SunMoonErrorDetail,
  BlqWriteReason,
} from "../pkg/sidereon.js";
export type { StationTideConstants } from "../pkg/sidereon.js";
export type { ImuGrade } from "../pkg/sidereon.js";
export type {
  SbasEncodeCoreDetail,
  SbasEncodeErrorDetail,
  SbasDeparture,
  SbasReencodedMessage,
} from "../pkg/sidereon.js";

// The RINEX observation, TDM, SP3 writer and ANTEX writer declarations are
// generated the same way, from the `typescript_custom_section` blocks in
// `src/rinex_obs.rs`, `src/tdm.rs`, `src/sp3.rs` and `src/antex.rs`.
export type {
  AntexWriteErrorDetail,
  CarrierPhaseShift,
  CorrectionStatus,
  GlonassCodePhaseBias,
  ObsAntenna,
  ObsDowngradeChange,
  ObsGlonassBias,
  ObsPrnObsCount,
  ObsProgramRunByDate,
  ObsReceiver,
  ObsSatelliteValues,
  ObsScaleFactor,
  ObsValue,
  RinexObsDowngrade,
  RinexObsWriteErrorDetail,
  PreciseSamplesErrorDetail,
  PreciseInterpolantArtifactErrorDetail,
  Sp3AccuracyCodeGroup,
  Sp3AccuracyValue,
  ClockRelativity,
  Sp3PositionClockAccuracy,
  Sp3PreciseEphemerisAccuracySample,
  Sp3PreciseEphemerisSample,
  Sp3SampleInstant,
  SelectedPositionClock,
  Ut1Validated,
  Sp3RawRecordAccuracy,
  Sp3RecordAccuracy,
  Sp3VelocityAccuracy,
  Sp3WriteErrorDetail,
  SsrCorrectionSize,
  SsrCorrectionSizeRefusalDetail,
  SsrOversizedCorrection,
  SsrCorrectedState,
  PppUnplacedObservation,
  PppUnplacedObservationReason,
  TdmComment,
  TdmDeparture,
  TdmErrorDetail,
  TdmFieldInput,
  TdmInputErrorKind,
  TdmLeniency,
  TdmMetadataResult,
  TdmParseResult,
  TdmPolicyInput,
  TdmPolicyLike,
  TdmWarning,
  TdmWritePolicyInput,
  TdmWritePolicyLike,
  TdmWriteResult,
} from "../pkg/sidereon.js";

// The RINEX clock, ANTEX, terrain, BLQ, positioning, RTCM encoder and SBAS
// declarations are generated the same way, from the
// `typescript_custom_section` blocks in `src/rinex_clock.rs`, `src/antex.rs`,
// `src/terrain.rs`, `src/tides.rs`, `src/spp.rs`, `src/rtcm.rs` and
// `src/sbas.rs`.
export type {
  AntexCalibration,
  AntexErrorDetail,
  AntexFrequency,
  AntexFrequencyRms,
  AntexHeader,
  AntexOuterComment,
  AntexPcvSample,
  AntexPcvType,
  AntexVersion,
  BlqParseErrorDetail,
  BlqParseReason,
  BlqWriteErrorDetail,
  CoreErrorDetail,
  CoreErrorExactFloat,
  CoreDtedTileErrorDetail,
  CoreIonexEpochErrorDetail,
  CoreSbasEncodeCause,
  CoreRtcmMsmOptionalProblem,
  CoreRtcmDepartureDetail,
  CoreRtcmEncodeCause,
  CoreRtcmLnavRecordError,
  CoreRtcmConversionCause,
  BiasDepartureDetail,
  BiasError,
  BiasErrorDetail,
  BiasNoticeDetail,
  BiasSet,
  DtedHorizontalDatum,
  AnomalyErrorDetail,
  DataCatalogErrorDetail,
  DomainErrorDetail,
  ElementsErrorDetail,
  EquinoctialErrorDetail,
  ExactCacheErrorDetail,
  ExactFloatDetail,
  FrameDomainErrorDetail,
  PropagationErrorDetail,
  ScenarioErrorDetail,
  FdeGeometryQuality,
  FdeUnresolvedSolution,
  OceanLoadingBlqBlock,
  OceanLoadingBlqBlockInput,
  OceanLoadingBlqComment,
  ObservablesErrorDetail,
  PositioningError,
  PositioningErrorDetail,
  PreciseObservableStateBatch,
  PreciseObservableStateElementResult,
  TimeModelErrorDetail,
  TimeModelCoreErrorDetail,
  TimeOffsetErrorDetail,
  QualityError,
  QualityErrorDetail,
  QualityErrorKind,
  RinexClockCivilEpoch,
  RinexClockDiagnostic,
  RinexClockErrorDetail,
  RinexClockHeaderField,
  RinexClockHeaderRecord,
  RinexClockInstant,
  RinexClockLeniency,
  RinexClockNotice,
  RinexClockPointInput,
  RinexClockPointRowInput,
  RinexClockRecord,
  RinexClockRecordInput,
  RinexClockRecordReading,
  RinexClockSeriesRowInput,
  RinexClockSkip,
  RinexClockTimeSystemStatus,
  RinexClockWriteDeparture,
  RinexClockWritePolicyInput,
  RinexClockWritePolicyLike,
  RinexClockWriteResult,
  RtcmEncodeErrorDetail,
  RtcmEncodeCoreDetail,
  RtcmConversionCoreDetail,
  RtcmRecordKindDetail,
  RtcmMsmMaskProblem,
  RtcmMsmOptionalProblem,
  RtcmVtecProblem,
  RtcmLnavRecordError,
  RtcmHelmertTransformation,
  RtcmHelmertTransformationInput,
  RtcmProjection,
  RtcmProjectionInput,
  RtcmProjectionParameters,
  RtcmResidualGrid,
  RtcmResidualGridInput,
  SbasUnassignedMaskCorrections,
  SolutionValidationDetail,
  SolveStatus,
  SppRejectedSatellite,
  SppRequest,
  QzssClock,
  TroposphereModel,
  RinexSppOptions,
  RinexSppEpochInputs,
  StaticSolveOptions,
  NmeaDiagnostics,
  PppCorrectionOptions,
  CodeBiasOptions,
  PppCorrectionEpoch,
  PppCorrectionEpochVector,
  PppCorrectionSatelliteScalar,
  PppCorrectionSatelliteVector,
  PppCorrections,
  PppCorrectionsErrorDetail,
  SppRejectionReason,
  SppSolveMetadata,
  StaticSolveMetadata,
  Sgp4ExactFloat,
  Sgp4ExactInteger,
  Sgp4ExactJulianDate,
  Sgp4InputErrorKind,
  Sgp4ErrorCause,
  Sgp4ErrorDetail,
  TleErrorCause,
  TleErrorDetail,
  TleRecordIssueDetail,
  DecayLatchedErrorCause,
  DecayLatchedErrorDetail,
  LookAngleErrorCause,
  LookAngleErrorDetail,
  PassErrorCause,
  PassErrorDetail,
  TrfBackendErrorCause,
  TrfErrorCause,
  TleFitErrorCause,
  TleFitErrorDetail,
  Sgp4FitElements,
  Sgp4OmmEpoch,
  Sgp4OmmComments,
  Sgp4OmmSpacecraft,
  Sgp4OmmCovariance,
  Sgp4OmmUserDefined,
  Sgp4FitOmm,
  Sgp4FitStatistics,
  Sgp4BestEffortFit,
  Sgp4BatchErrorCause,
  Sgp4BatchErrorDetail,
  Sgp4OperationErrorDetail,
  Sgp4OperationError,
  TerrainHeightBatchEntry,
  TerrainLookupErrorDetail,
} from "../pkg/sidereon.js";
